- hosts: all
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
    homebrew_packages:
      - { name: lua }
      - { name: vim, install_options: with-lua }
      - { name: readline }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: python }
      - { name: coreutils }
      - { name: git }
      - { name: zsh, install_options: without-etcdir }
      - { name: wget }
      - { name: curl }
      - { name: lynx }
      - { name: npm }
      - { name: ag }
      - { name: cmake }
      - { name: automake }
      - { name: autoconf }
      - { name: pkg-config }
      - { name: ctags }
      - { name: tree }
      - { name: nkf }
      - { name: jq }
      - { name: go, install_options: cross-compile-common }
      - { name: direnv }
      - { name: rbenv }
      - { name: plenv }
      - { name: pyenv }
      - { name: ruby-build }
      - { name: perl-build }
      - { name: sqlite }
      - { name: redis }
      - { name: imagemagick }
      - { name: packer }
      - { name: socat }
      - { name: tmux }
      - { name: pwgen }
      - { name: git-now }
      - { name: nmap }
      - { name: reattach-to-user-namespace }
      - { name: graphviz }
      - { name: awscli }
  tasks:
    - name: homebrewのtapリポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: homebrewをアップデート
      homebrew: update_homebrew=yes

    - name: brewパッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result

    - name: brewパッケージの情報保存ディレクトリを作成
      file: path=brew_info state=directory

    - name: brewパッケージの情報を保存
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

